# Generated by Django 5.2.4 on 2025-08-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
    ]
