# Generated by Django 5.2.4 on 2025-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
