# Generated by Django 5.2.4 on 2025-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nu_pie_full',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sell',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
