# Generated by Django 5.2.4 on 2025-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_nu_pie_full_product_price_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_sell',
        ),
        migrations.AlterField(
            model_name='product',
            name='nu_pie_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
