# Generated by Django 5.2.4 on 2025-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_product_price_sell_alter_product_nu_pie_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
