# Generated by Django 5.2.4 on 2025-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_price_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_money',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
