# Generated by Django 5.2.4 on 2025-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_confirm_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='abakozi',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
