# Generated by Django 5.2.4 on 2025-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_abakozi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abakozi',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
