# Generated by Django 5.2.4 on 2025-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_abakozi_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employees_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
